### ISSUE TITLE
`Table::len()` is not computing the right size because of stale entries

### ISSUE THREAD

**Issue by yihozhang** [egraphs-good/egglog#120]
This causes issues with `print-size` and the printed summary. I made an ad hoc fix locally for `print-size` which the artifact relies on but we need a more careful fix.

**Comment by mwillsey** [comment]
I think the `Table` stuff has drifted a little far from my understanding... maybe @ezrosent can say.

**Comment by ezrosent** [comment]
`vals.len() - n_stales` will work, just be careful... there are where we really want vals.len() here, basically any point where you want to use the output as a numeric offset into the table. For example:

* All the calls to `self.len()` in table, should be migrated to self.vals.len() if you make the change.
* [this call](https://github.com/mwillsey/egg-smol/blob/main/src/function/mod.rs#L227) to update_indexes should be vals.len()
* [this call](https://github.com/mwillsey/egg-smol/blob/main/src/function/mod.rs#L253) is used to scan the whole table, by offset (can't use a normal iterator for borrow checker reasons)

My guess is that all calls to `Table::len` except the ones where we want the size of the data-set actually do want the the number of valid table offsets.

Maybe rename `Table::len` to `Table::num_offsets` and migrate those calls first?
