### ISSUE TITLE
Visualization of EGraph State

### ISSUE THREAD

**Issue by saulshanabrook** [egraphs-good/egglog#144]
I am starting to look into adding some interactive visualizations to egglog-python and wanted to open an issue here, thinking I might start with adding some visualizations upstream.

I think could be useful for explaining e-graphs to new audiences and developing a mental model in particular for how egglog works.

To start with, I was hoping to generate graphs similar to those on the [`egg`](https://egraphs-good.github.io/) website:

![](https://egraphs-good.github.io/egraphs.svg)

I have started to look through the internal structure to pull out the pieces I would need to traverse:

* `EGraph` struct
  * `functions`: `HashMap<Symbol, Function>`
    * In the `Function` struct, can get the 
    *  In the `Function` struct, the `nodes.vals` (`Vec<(Input, TupleOutput)>`)  returns a number of input (list of `Value`s) output (`Value`) pairs which define the nodes of the function
         * `Value` has a `tag` which defines which type it is and a `bits` to store the value. For the primitive types, this is the value. For an "Eq Sort" i.e. user defined type, this is a lookup in the `unionfind`
 * `unionfind`: `UnionFind`
   * `parents`: Vector where each index is an ID and the values point to the parent item. 

For `egglog`, I was thinking I could generate something in a `.dot` syntax, which could be visualized using the `graphviz` CLI as well as [in the browser](https://github.com/hpcc-systems/hpcc-js-wasm/). I could either generate the strings directly or rely on a rust library like [`graphviz-rust`](https://github.com/besok/graphviz-rust) to create them.

To create the graph I was going to try:

1. Traversing the `parents` in the `unionfind` structure to create a cluster per union, with a node in each cluster item.
2. Traversing all the values of each all functions, setting the text of each node to the function name, and adding an edge between the output and each input. For non-eq/primitive nodes, I would create a new node in the graph for each. For output primitive nodes, I would have the text be the value as well as the function.

I am not sure how legible this will be, but wanted to see how it works out for some of the examples.

If this does work out, then I would try extending to some interactive formats. I have had luck in the past using [cytoscape.js](http://js.cytoscape.org/) for large graph visualization of programs (see https://github.com/vega/editor/pull/1023/).

**Comment by mwillsey** [comment]
In my experience the e-graph quickly becomes too big to visualize, unfortunately. That was my inspiration for the "extract variants", as some kind of alternative to full state visualization.

**Comment by saulshanabrook** [comment]
Yeah, I have found that graphviz static layouts become quite unreadable with large numbers of nodes.

I have had luck with interactive visualizations for graphs with a larger number of nodes, which support interactive filtering (i.e. clicking on a node to filter to its ancestors/descendants):

https://user-images.githubusercontent.com/1186124/236923605-e9b69d98-3a76-422f-84fa-7372fe419ebf.mov


I was thinking of trying something simpler with graphviz first, just to make sure I am understanding the data model properly, and that could work with small example graphs, and then implement some interactive viz after, for more real-world use cases?

**Comment by mwillsey** [comment]
I'm not opposed to it, in fact it sounds very cool, but I will say that I don't think this is high on our todo list at the moment.

**Comment by mwillsey** [comment]
Ok! I'm going to close this as an issue then, as it's not really actionable from our side.
