### ISSUE TITLE
Integer overflow in `semi_naive_set_function_with_proofs`

### ISSUE THREAD

**Issue by ezrosent** [egraphs-good/egglog#148]
Enabling proofs for the `semi_naive_set_function` test results in an integer overflow, apparently in the generated proofs code; with `RUST_LOG=debug` enabled:

```
$ cargo test semi_naive_set_function_with_proofs
...
[2023-06-01T03:26:52Z DEBUG egg_smol::gj] Query: (Cons__ p1 pl p) (ProofCost__ p1 cost) (ProofListCost__ pl cost2) where (+ cost cost2 v15_____) 
    New atom: (ProofListCost__ pl cost2) 
    Vars: p1 pl p v15_____ cost cost2
    Program
     Intersect @ 1   0: Cons__.1  2: ProofListCost__.0
     Intersect @ 0   0: Cons__.0  1: ProofCost__.0
     Intersect @ 2   0: Cons__.2
     Intersect @ 5   2: ProofListCost__.1
     Intersect @ 4   1: ProofCost__.1
     Call Prim(+) [Var("cost"), Var("cost2"), Var("v15_____")] false
thread 'semi_naive_set_function_with_proofs' panicked at 'attempt to add with overflow', src/sort/i64.rs:32:61
```
I think other desugaring is generating costs that are really large. It seems like we shouldn't be using `i64` and `+` for this if these costs really need to be that high, instead we could look at:

* `f64`
* `Option<i64>` where `None` is "positive infinity"
* Use saturating addition.

Not sure which of these would be easiest for the proofs code.

**Comment by saulshanabrook** [comment]
FWIW I think https://github.com/egraphs-good/egglog/pull/141 addresses some of this by adding a no-extract option for costs which is like positive infinity. https://github.com/egraphs-good/egglog/pull/140 was a hacky was to get around it by just reducing the high cost.

**Comment by yihozhang** [comment]
Closing since proof has been removed and the rules causing integer overflows are no longer here.
