### ISSUE TITLE
Vec include getting items and length?

### ISSUE THREAD

**Issue by saulshanabrook** [egraphs-good/egglog#152]
I was looking at the Vec sort and as far as I can tell it doesn't have a way to retrieve an item at a certain index or update an item at a certain index? It seems to only contain a way to check if an item exists.

It seems similar to a set then, but maybe allowing duplicates and ordered.

I was curious if you would be open to a PR which adds the ability to get an item from a particular index as well as one which returns the length.

**Comment by yihozhang** [comment]
> I was curious if you would be open to a PR which adds the ability to get an item from a particular index as well as one which returns the length.

Definitely! The Vec sort has the existing set of APIs only because the test suites only require those. More is definitely welcome.
