### ISSUE TITLE
Unable to build egglog

### ISSUE THREAD

**Issue by RafaeNoor** [egraphs-good/egglog#166]
Hello!
I am trying to build the repository however I'm running into some issues. First when I build it using `make all` it gives an error when trying to compile the target `test`:

When I comment out those lines, the build progresses and then fails at the following point:
```
error[E0658]: use of unstable library feature 'int_log'
  --> src/sort/i64.rs:45:67
   |
45 |         add_primitives!(eg, "log2" = |a: i64| -> i64 { (a as i64).ilog2() as i64 });
   |                                                                   ^^^^^
   |
   = note: see issue #70887 <https://github.com/rust-lang/rust/issues/70887> for more information

error[E0658]: use of unstable library feature 'is_some_with'
    --> src/lib.rs:1029:42
     |
1029 |                 if self.get_sort(&value).is_some_and(|sort| sort.is_eq_sort()) {
     |                                          ^^^^^^^^^^^
     |
     = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `egglog` due to 2 previous errors
```

I'm guessing the latter issue may be something to do with my Rust configuration, I'm not too familiar with Rust.

**Comment by mwillsey** [comment]
As of a recent commit, you need to use a Rust version of at least 1.70. Try running rustup update!

**Comment by RafaeNoor** [comment]
That appears to have fixed it!
The nextest target still fails with the following error:
```
error: no such command: `nextest`

	Did you mean `test`?

	View all installed commands with `cargo --list`
Makefile:16: recipe for target 'test' failed
make: *** [test] Error 101
```
But after removing that target it builds through.

**Comment by mwillsey** [comment]
Sorry, yes we should update the docs on this. nextest is an alternative
testing harness for Rust. You  can just type cargo test and it’ll work, but
nextest has some fancier features that we use for our testing suite.
