### ISSUE TITLE
Extract no longer prints in the frontend

### ISSUE THREAD

**Issue by jbachurski** [egraphs-good/egglog#178]
Thanks for the amazing project! 
I was just experimenting with `egglog`, and may have missed the exact change, but it looks like from the moment #176 was merged the command `extract` (or rather its new name, `query-extract`) no longer prints to the standard output. 
To reproduce, run any example with `query-extract` - like https://egraphs-good.github.io/egglog/?example=eqsolve. No output with terms/costs is printed.
I think the output is printed to the browser console instead, but that's somewhat inconvenient to use. Is there a workaround?

**Comment by yihozhang** [comment]
I think it makes sense to print the extracted program to stdout, so we should probably add this back? cc @oflatt

**Comment by oflatt** [comment]
Yes it should print to stdout! Sorry about that

**Comment by oflatt** [comment]
Fixed by #183
