### ISSUE TITLE
TermDag Confusion

### ISSUE THREAD

**Issue by saulshanabrook** [egraphs-good/egglog#193]
I am taking a closer look at the [`TermDag`](https://github.com/egraphs-good/egglog/blob/main/src/termdag.rs) introduced by @oflatt in https://github.com/egraphs-good/egglog/pull/176 and am a bit confused on how the different indices function in it.

My understanding from reading the code is that:

* Each `App` term points to its arguments with an integer, that represents an index in the `nodes` vec ([cite](https://github.com/egraphs-good/egglog/blob/3f7c3fed7dde072dfc8c97b6c2dfba257a4deb7c/src/termdag.rs#L101))
* When a node is added, the hashcons is updated with the term pointing to the index of the term in the vec.

So am I understanding things correctly that the `hashcons` provides no additional information over the `nodes` vector itself? And it serves just as a way to do faster lookups from each term to its index?

Originally when I saw the `hashcons` structure, I thought it meant something about e-classes, but looking at the implementation that does not seems to be the case.

If this is so, I am happy to add a PR with some comments to make things clearer.

**Comment by oflatt** [comment]
Yes, your understanding is correct. The hashcons is just an index so we can look up the id for a given term. 
In the future one of my goals is to write more comments and documentation for egglog, for now I would appreciate a PR that makes things clearer.
