### ISSUE TITLE
`vscode/eggsmol-1.0.0/package.json` refers wrong syntax file

### ISSUE THREAD

**Issue by hatoo** [egraphs-good/egglog#203]
https://github.com/egraphs-good/egglog/blob/0f777d6700d860e21137ef2cfbdbe5f7ae31b701/vscode/eggsmol-1.0.0/package.json#L34

There is only `syntaxes/eggsmol.tmLanguage.json` .
`"path"` or filename should be updated.

**Comment by mwillsey** [comment]
Yes, I think the vscode plugin is stale or broken for now. I'd like to revamp or remove it.

**Comment by hatoo** [comment]
The original VScode extension was removed #312
