### ISSUE TITLE
Dual front end for egglog

### ISSUE THREAD

**Issue by yihozhang** [egraphs-good/egglog#216]
Currently, egglog does repetitive work by having two front-end compilers. For example, if one adds a rule with the `add_rule` function, it will directly call the query compiler at `typecheck.rs::typecheck_query`. However, if the rule is added via `run_program`, then it will go through the desugaring process, which transforms the rule into a normal form, then resugars it, and again sends it to the query compiler.

There are several options here:
* The fact that we need to transform to a normal form and recover from that seems to suggest we can just get rid of this normalization process.
* We can also make sure that everything goes through the normalization process and simplify the `typecheck` module by assuming the input is normalized.

**Comment by oflatt** [comment]
I'm strongly in favor of option 2 over option 1.
The normalization pass simplifies the interface to the back end. In addition, it enables easier analysis and encodings (such as proofs, which are still in a branch)

**Comment by yihozhang** [comment]
Ideally, proofs should just be some user-defined macros... but I see why that would be very difficult.

Another thing is that `typecheck` itself also produces a normalized IR: for example, for query
```
(rule ((= (f x) (f y))
       (= (f y) (f z))
       (= (+ x y) z)
       (= w (+ x z)))
      ())
```
The `NormRule` form is 
```
(rule ((= v0___ (f x))
           (= v2___ (f y))
           (= v1___ v2___)
           (= v3___ (f z))
           (= v4___ (+ x y))
           (= w (+ x z))
           (= v2___ v0___)
           (= v3___ v1___)
           (= v4___ z))
          ()
```
While `Query` produced by `typecheck` is
```
(f x v0___) 
(f z v0___) 
(f y v0___) 
    where 
(+ x y z)
(+ x z w)
```
which is arguably clearer.

Also, it is a bit unusual to have the distinction between `AssignVar` (let-bound var definition) and `ConstrainEq` (equality check) in a relational query compiler front end.

I'm planning to work on this issue and front-end related issues like #133 next week in parallel to eggcc, and I'm trying to figure out the best front-end IR that works for egglog's use case (a design doc maybe). @oflatt any recommendations on where I can get started to understand your proof code to see what normalized form we need?

**Comment by oflatt** [comment]
I agree it is easier to view normalized form from `typecheck`, but reading the IR is a separate problem in my mind and the reason I wrote the `--resugar` flag.

The reason `AssignVar` exists is that there are situations where one variable is bound and the other isn't, and there are also situations where both are already bound (which is when we use `ConstrinEq` and this distinguishes the two.


Here is the proofs file on my proofs branch:
https://github.com/oflatt/egg-smol/blob/oflatt-term-proofs/src/proofs.rs
Lmk if you have questions. You can get proof outputs with the `--proofs` flag and `--resugar` flag and read them

**Comment by yihozhang** [comment]
@oflatt Thanks for the pointer! I'll take a look at it.

I think I still don't understand why we need `AssignVar`. If you look at the output of `typecheck`, I guess you can say v0___ is bounded in the first atom (`(f x v0___)`) and checked in the rest, but it does not really matter here- they are just conjunctive queries. We can discuss more in person.
