### ISSUE TITLE
Rule Applied Twice Bug

### ISSUE THREAD

**Issue by saulshanabrook** [egraphs-good/egglog#229]
I am encountering a bug where the actions for the actions in a rule will trigger twice in one execution. Normally, this is fine, if the rules are monotonic. But if you have a function that returns a primitive and has a merge function, then setting it twice could lead to incorrect results.

## Reproducible use case

Here is a way to reproduce this bug. It's not super minimal, but it is a lot more minimal than the Python code I extracted it from.

What it does is turns an expression graph into a string of statements of each expression. 

It works bottom-up, generating a string for each expression and also adding to the statements, if the expression defines a new variable, and incrementing the gensym.

It basically works, but it seems like the actions in the multiply rule are run twice on the same nodes instead of just once.

```lisp
(function statements () String :merge (+ old new) :default "")
(function gensym () i64 :merge (+ old new) :default 0)
(sort Math)
(function Num (i64) Math)
(function Var (String) Math)
(function Add (Math Math) Math)
(function Mul (Math Math) Math)
(function expr (Math) String)
(rule ((= x (Var s)))
      ((set (expr x) s))
         )
(rule ((= x (Num i)))
      ((set (expr x) (to-string i)))
         )
(rule ((= x (Add y z))
       (= y_expr (expr y))
       (= z_expr (expr z)))
      ((set (expr x) (+ "_" (to-string (gensym))))
       (set (statements) (+ (+ "_" (to-string (gensym))) " = " y_expr " + " z_expr "
"))
       (set (gensym) 1))
         )
(rule ((= x (Mul y z))
       (= y_expr (expr y))
       (= z_expr (expr z)))
      ((set (expr x) (+ "_" (to-string (gensym))))
       (set (statements) (+ (+ "_" (to-string (gensym))) " = " y_expr " * " z_expr "
"))
       (set (gensym) 1))
         )
(Mul (Num 2) (Add (Var "x") (Num 3)))

(run 3)

(extract (statements))
(extract (expr (Mul (Num 2) (Add (Var "x") (Num 3)))))
```

It should print out:

```
"_0 = x + 3
_1 = 2 * _0
"
"_1"
```

But it duplicates the second statement instead:

```
"_0 = x + 3
_1 = 2 * _0
_1 = 2 * _0
"
"_1"
```

**Comment by saulshanabrook** [comment]
I am starting to debug this issue.

I added a few `println`'s to see try to pinpoint what's going on. Here is a bit of the trace that I think is thee problem area:

```
Running Program([Load(Subst(2)), Load(Subst(7)), Set("expr"), Load(Subst(3)), Set("statements"), Literal(Int(1)), Load(Stack(0)), Set("gensym")])
Running Program([Literal(String("_")), CallFunction("gensym", true), Load(Stack(1)), CallPrimitive(Prim(to-string), 1), Load(Stack(0)), Load(Stack(2)), CallPrimitive(Prim(+), 2), Load(Subst(2)), Load(Stack(3)), Set("expr"), Literal(String(" = ")), Literal(String(" * ")), Literal(String("\n")), Load(Stack(3)), Load(Stack(4)), Load(Subst(4)), Load(Stack(5)), Load(Subst(3)), Load(Stack(6)), CallPrimitive(Prim(+), 6), Load(Stack(7)), Set("statements"), Literal(Int(1)), Load(Stack(8)), Set("gensym")])
  Concating: "_"
  Concating: "1"
  - > res: "_1"
  Concating: "_1"
  Concating: " = "
  Concating: "2"
  Concating: " * "
  Concating: "_0"
  Concating: "\n"
  - > res: "_1 = 2 * _0\n"
Running Program([Load(Subst(0)), Load(Subst(1)), CallPrimitive(Prim(+), 2)])
  Concating: "_0 = x + 3\n"
  Concating: "_1 = 2 * _0\n"
  - > res: "_0 = x + 3\n_1 = 2 * _0\n"
Running Program([Load(Subst(2)), Load(Subst(7)), Set("expr"), Load(Subst(1)), Set("statements"), Literal(Int(1)), Load(Stack(0)), Set("gensym")])
Running Program([Load(Subst(0)), Load(Subst(1)), CallPrimitive(Prim(+), 2)])
  Concating: "_0 = x + 3\n_1 = 2 * _0\n"
  Concating: "_1 = 2 * _0\n"
  - > res: "_0 = x + 3\n_1 = 2 * _0\n_1 = 2 * _0\n"
```

The last concat is the incorrect one, the `_1` line shows up twice. The program before it is run I assume in the merge function for `statements`. The issue is that this has already been run.

**Comment by yihozhang** [comment]
I think this is related to #93. Basically, because there are `set`s in actions, semi-naive evaluation needs to duplicate the rule to ensure the correctness of semi-naive evaluation. If you run the rule with `--naive` flag, the output is as expected. In general, however, to ensure correctness, actions should be idempotent, and the merge function should either be a `max` operation or `union`, both of which are idempotent.

**Comment by oflatt** [comment]
I agree with @yihozhang, and I also think that my proposal in #228 would fix this problem

**Comment by saulshanabrook** [comment]
>  If you run the rule with --naive flag, the output is as expected.

I gave this a go, and it's true that this will not have the double output. However, if you change it to more than `(run 3)` like (run 10)`, the `--naive` run will have many more duplicate outputs. Whereas the non-naive flag will only have the one duplicate output. 

So to recap:

* With the default (seminaive) it will "properly" saturate  after running the action once, but in the one time it runs it it mistakenly duplicates the merge command
* With `--naive` it will not saturate, infinitely adding to the string, but each time it adds it will only add it once.

**Comment by saulshanabrook** [comment]
I think I will close this with the understanding that non-monotonic merge functions are undefined behavior and they should not be relied on!
