### ISSUE TITLE
Merge on user defined sorts defined behavior?

### ISSUE THREAD

**Issue by saulshanabrook** [egraphs-good/egglog#237]
I found that defining a custom `merge` function on user-defined sorts is currently supported and changes them to be treated like primitives (i.e. you must use `set` instead of `union`):

```
(datatype Math
  (Num i64)
  (Var String)
  (Add Math Math)
  (Mul Math Math))

(function inc (Math) Math :merge old)

(let expr1 (Mul (Num 2) (Add (Var "x") (Num 3))))

(set (inc expr1) (Var "y"))
(set (inc expr1) (Var "x"))
```

If I understand it correctly, this comes from the fact that user-defined sorts have their merge function defined as the union operator of the eq-class by default, so when you override it, it is no longer an equality sort but acts like a primitive, with only one value.

I just wanted to check whether this was intentional behavior and something I can rely on, or whether its a quirk of the current implementation (i.e. will it be disrupted by incoming refactoring PRs?)

I am thinking about using it to define a "parent" node when compiling an expression tree, so that each expression only gets compiled into the first parent that finds it.

**Comment by oflatt** [comment]
This is intentional behavior and actually is used by my new PR #233 
Merge functions are still quite confusing though, so their semantics may change in the future (be warned)

**Comment by saulshanabrook** [comment]
> Merge functions are still quite confusing though, so their semantics may change in the future (be warned)

Good to know! I'll close this then for now.
