### ISSUE TITLE
Add ability to run multiple rulesets simultaneously OR put a rule in multiple rulesets

### ISSUE THREAD

**Issue by gussmith23** [egraphs-good/egglog#246]
It would be nice to be able to keep granular rulesets (e.g. a ruleset for typing judgements, a ruleset for program manipulations) but be able to run them all together. As far as I can tell, `run` can only take a single ruleset arg. Another way to do this would be to assign a rule to multiple rulesets (e.g. `typing` and `all`) and have one ruleset that contains all rules.

**Comment by saulshanabrook** [comment]
I believe you can run a sequence of rulesets repeatedly, or until they are saturated?

https://github.com/egraphs-good/egglog/blob/43a6a3ba0e84954160d4eb8eda1ac5bdf23da310/tests/schedule-demo.egg#L18-L21

So like this?

```
(run-schedule
      (saturate (seq
            (run typing)
            (run other))))
```

**Comment by yihozhang** [comment]
Running two rules sequentially is different from running them all together,
though. The difference might not matter in many cases, but there could be
exceptions.

**Comment by gussmith23** [comment]
Thanks to the both of you. What Saul posted should be good enough for me for now, but yeah, seems like Yihong is right about the details. Perhaps something that allows you to concatenate two rulesets to make a new ruleset would be nice!

Unsure if you guys wanna take further action on this. Feel free to close.

**Comment by yihozhang** [comment]
Multiple rulesets can be simultaneously run with combined-ruleset now (#362).
