### ISSUE TITLE
How to enumerate top-k?

### ISSUE THREAD

**Issue by cloudhan** [egraphs-good/egglog#257]
The `extract` command extract the top-1 (cheapest) values. 
https://github.com/egraphs-good/egglog#extract-command
> The extract queries the store to find the cheapest values matching the expression.

However, if each operation is not as simple as an instruction (but as complex as a small program), the cost may not be that reliable when puting all of them together. As a program, the cost depends highly on its implementation and the hardware environment. So we might resort to runtime tuning, and select the best based on the actual timing. This requires to propose a set of promising candidates, aka, top-k values. Is it possible in the current setting?

**Comment by oflatt** [comment]
I think that might be a little challenging to implement, I'm not actually sure how it would be done.
However we do have already a `:variants` option that gives you different variants of the program. It does this by picking different e-nodes in the e-class, but the smallest option for the children. In other words, it will try to pick different constructors

**Comment by oflatt** [comment]
Closing this for now, but we can consider improving `:variants` or design a "top-k" algorithm in the future.
