### ISSUE TITLE
Computing sums with :merge

### ISSUE THREAD

**Issue by cormacrelf** [egraphs-good/egglog#286]
Below is the code for a sum. I have read that :merge should be monotonic -- clearly here it is, being (+ old new).

Unfortunately you can't use a sum as your merge function. Because at some point during a sum, the two things being added might be the same value. And in that case, :merge does not execute. So you lose one of them.

This does not replicate in the demo running on WebAssembly. I think it's due to the non-determinism in the order the rules get applied & actions get run. In my mind :merge was supposed to be monotonic in order to survive this exact non-determinism, so that seems fine to me. I can reproduce the problem using `cargo install egglog` on a Linux machine.

```clojure
(datatype loc (var i64))
(function sum (loc) i64 :merge (+ old new) :default 0)
(datatype op (iadd loc i64))

(rule ((iadd loc amount))
      ((set (sum loc) amount)))

(let x (var 1))

(push)
(iadd x 100)
(iadd x 200)
(iadd x 300)
(run 1)
;; (check (= (sum x) 600)) ; fails!
;; it's still 300.
(extract (sum x))
(pop)

;; try in a different order
(push)
(iadd x 100)
(iadd x 300)
(iadd x 200)
(run 1)
(check (= (sum x) 600)) ; succeeds!
(extract (sum x))
(pop)

```

My impression is that `(iadd x 100) (iadd x 100)` should not (and indeed does not) produce 200, because the iadd is already in the database after you've inserted it once. So this is a dumb program. But it's just a demo of a problem I discovered in a more complex ruleset where that isn't an issue, i.e. there's a unique identifier for each "iadd".

**Comment by cormacrelf** [comment]
Oh, I guess addition doesn't form a lattice. It's not idempotent. Whoops. The docs did not lie.

Is there any way to do sums?

**Comment by yihozhang** [comment]
Yeah you are right sum does not form a lattice. And in egglog, your program will never reach a fixpoint because `(sum x)` will just repeatedly accumulating values from `iadd`,

If you are sure values to be summed does not contain duplicates, one workaround is to use sets:

```
(sort IntSet (Set i64))

(relation iadd (loc i64))
(function iadd-sets (loc) IntSet :merge (set-union old new))

(rule ((iadd loc x))
    (set (iadd-sets loc) (set-of x))
  :ruleset sum)

(relation sum (loc i64))
(rule ((= (iadd-sets loc) int-set))
    ((sum loc (set-sum int-set)))

(run-schedule 
  (repeat N 
    ;; for compute iadd-sets to fixpoint
    (saturate sum) 
    ;; the main rule set is idempotent now
    (run))
``` 

Unfortunately, `set-sum` is not something that has been implemented, so you have to either add it to your fork of egglog, or consider using the user-defined primitive interface as in #280.

**Comment by cormacrelf** [comment]
It does seem to saturate [like so](https://egraphs-good.github.io/egglog/?program=XQAAgAApAQAAAAAAAAAUGQgnfMUD9dO10cCXVCrUyva81zxk6BhX2AglqxPJuke24n1KgLVbDLU3fBtt0GY9WwHn3Ggkca2rDV3lMVLmpaXr0sGjTALS9g9WMg7bsQT_gMoW9K05kHQLRuCODXL3177wdJ9Mg_b9yIis-L_Am3Cq96CDCJnzYJ20dR6k8EqzFhP2IiA_djezrSHsuo21zQjpWFcZbhpUes2mWfdQuVvFcK_z0hNqxd8PsrYt3cfTmG7NHLX_-J6TmA%253D%253D).

I think I might just define a primitive that is a set of some concrete type (like a tuple of (iadd identifier, amount)) to sum over, exposing a primitive function that gets the sum back out. I have already used the user-defined primitive interface and it worked pretty nicely! I used it to make a type with a dynamic cost, roughly like `(datatype X (cost i64) :cost (get-the-i64-back-out))` except it works. It did need a couple of things made `pub` which I will PR separately.

Thanks for your help!

**Comment by yihozhang** [comment]
> It does seem to saturate [like so](https://egraphs-good.github.io/egglog/?program=XQAAgAApAQAAAAAAAAAUGQgnfMUD9dO10cCXVCrUyva81zxk6BhX2AglqxPJuke24n1KgLVbDLU3fBtt0GY9WwHn3Ggkca2rDV3lMVLmpaXr0sGjTALS9g9WMg7bsQT_gMoW9K05kHQLRuCODXL3177wdJ9Mg_b9yIis-L_Am3Cq96CDCJnzYJ20dR6k8EqzFhP2IiA_djezrSHsuo21zQjpWFcZbhpUes2mWfdQuVvFcK_z0hNqxd8PsrYt3cfTmG7NHLX_-J6TmA%253D%253D).

Ohh I see. This is probably because of the semi-naive optimization egglog does by default.

>  It did need a couple of things made pub which I will PR separately.

This sounds great! Let me know if you have any questions.
