### ISSUE TITLE
Remove egglog vscode extension, link to https://github.com/hatoo/egglog-language-server instead

### ISSUE THREAD

**Issue by oflatt** [egraphs-good/egglog#312]
The egglog team has decided that we should remove the egglog vscode extension in this repository, instead recommending people use https://github.com/hatoo/egglog-language-server.

We should remove it and link to https://github.com/hatoo/egglog-language-server  in the readme.

**Comment by oflatt** [comment]
Yes, I agree there are definite advantages and disadvantages to moving to `egraphs-good`
I think for now, the plan is to not move it for now. We can re-visit this question

**Comment by saulshanabrook** [comment]
> I think for now, the plan is to not move it for now. We can re-visit this question

Sounds good! I would be curious to hear the rationale/any feedback on the decision to move the python repo to the org.
