### ISSUE TITLE
Neovim plugin

### ISSUE THREAD

**Issue by segeljakt** [egraphs-good/egglog#354]
Hi, I would just like to notify that I have created a Neovim plugin for Egg using tree-sitter that currently supports syntax highlighting and local variable highlighting:

https://github.com/segeljakt/tree-sitter-egg

Would it be ok to add a reference to it in the README?

This is the tree-sitter grammar in case anyone is interested: https://github.com/segeljakt/tree-sitter-egg/blob/master/grammar.js

**Comment by yihozhang** [comment]
Thanks for making the Neovim plugin! Created a PR for this
