### ISSUE TITLE
Web demo should show logs

### ISSUE THREAD

**Issue by oflatt** [egraphs-good/egglog#358]
At some point, @yihozhang refactored the output of our tool to be cleaner. There is a separation between logging and printing important information.
However, for the web demo we would like to see more verbose information. For example, nothing is printed for a `check` command. We should add the logging information back to the web demo. We should also make logs accessible somehow- perhaps we should print results to stderr and logs to stdout?

**Comment by yihozhang** [comment]
Fixed by #365
