### ISSUE TITLE
Refactor `print_function` to use a new function called `dump_function`

### ISSUE THREAD

**Issue by gussmith23** [egraphs-good/egglog#366]
On the Rust side, I would like to have access to the functions printed by `print_function`. @oflatt suggested a simple refactor, adding a `dump_function` function which dumps the Term objects, and then refactoring `print_function` to use `dump_function`. Then I can use `dump_function` to achieve my own goal.

Feel free to assign to me.

**Comment by gussmith23** [comment]
Turns out this is actually done! `EGraph::function_to_dag`.

Opened an issue to document the function: #367

**Comment by saulshanabrook** [comment]
Oh cool! There is an open issue in the Python bindings to expose print function, but I wasn't sure if I could get at the data. Nice to know that it's possible https://github.com/egraphs-good/egglog-python/issues/124
