### ISSUE TITLE
Mitigating blowup with Associative-Commutative rules ?

### ISSUE THREAD

**Issue by remi-delmas-3000** [egraphs-good/egglog#410]
Hi, 

I'm using egglog to detect and eliminate redundancy in SMT-lib formulas encode symbolic execution of small programs and contain a lot of conjunctions/disjunctions. The rewriting blow ups due the AC rules I added to my egglog model,

I've used other systems that use AC-completion algos, or that represent AC symbols as n-ary constructors applied over hashsets of terms and internally use hashset union/hashset equality to flatten/check equality

Are there any workaround or encoding techniques I could use in egglog to mitigate the blowup ?

**Comment by yihozhang** [comment]
I think in general this is an under-researched open problem of EqSat! There are scheduling tricks like running AC rules less often than other rules, but there have not been a systematic approach. Phil has some [interesting ideas](https://www.philipzucker.com/linear_grobner_egraph/) on AC-EqSat that may mitigate the blowup, but this has not been implemented in egglog.
