### ISSUE TITLE
Pattern-local `let` binding?

### ISSUE THREAD

**Issue by gussmith23** [egraphs-good/egglog#476]
(I'm not sure if this is still the best place to post questions)

Sorry if I've asked this before, but is there a way to do pattern-local `let` bindings? For example, if i'm rewriting `expr` into `(f (g x y) (g x y))` it would be nice to do something like `(let ([e (g x y)]) (f e e))`. However, the existing let bindings currently make global names (at least that was true last time I checked).

Thanks!

**Comment by gussmith23** [comment]
I could see them being useful on both sides of the rule. LHS like in the
case you showed. But if your RHS is even moderately complex, but you don't
want to introduce global names, you need them there too.

**Comment by oflatt** [comment]
I think there may be a miscomunication here. Here is the syntax of an egglog rule:
`(rule LHS RHS)` where the left hand side `LHS` is a list of patterns to be matched and the rhs `RHS` are the actions to be run. In my last example, I showed intermediate variables in the RHS.

For the LHS, you can also bind intermediate variables using equality constraints:

````
(rule ((= myvar (g x y))
            (f myvar myvar))
           (...))
```

If you want more examples, see the `tests` folder in this repo or look at the source code of eggcc

**Comment by gussmith23** [comment]
Ah whoops, forgot about the `(= local-binding ...)` trick for LHS.

And yes, I got my LHS and RHS confused, hahah. I'm not good with lefts and rights...

Ok, so to make this super clear:

Local bindings on the left-hand side are handled by the `(= local-binding ...)` trick.

Local bindings on the right-hand side are still confusing for me though. The rule you posted:
```
(rule ((f x y))
         ((let myvar (g x y))
           (f myvar myvar)))
```

Does this not add `myvar` to a global name scope? I thought this is how it was in the past, at least. I'm explicitly trying to avoid cluttering that global scope. 

Thank you!

**Comment by yihozhang** [comment]
> Does this not add myvar to a global name scope?

Nope! `let` bindings are always local when used in a rule. Global bindings need to be declared at the top level.

**Comment by gussmith23** [comment]
Oh, that's great!! I have no clue where my assumption came from that they went into a global scope. Perfect, this will make my rules much cleaner!
