### ISSUE TITLE
Print Line Number on Parse Error

### ISSUE THREAD

**Issue by philzook58** [egraphs-good/egglog#64]
Conversion of character number to line col number would be a much more pleasant programming experience. I get around it by installing an extension in my vscode editor that prints character number. Bonus mode if one can print the line with little squiggles under the problem. I attempted to do this a few months back based on these comments https://github.com/lalrpop/lalrpop/issues/323#issuecomment-366681594 but got lost somewhere in  custom error implementation egg-smol has.

**Comment by mwillsey** [comment]
I think we should target using something like [miette](https://docs.rs/miette/latest/miette/index.html).

**Comment by yihozhang** [comment]
Closing given #199 and #398
